### ISSUE TITLE
Format as an ITK module to enable use as a library

### ISSUE THREAD

**Issue by thewtex** [plooney/kretz#8]
In order for other projects to use the code, it should be made available as an ITK Module. This will provide the required CMake configuration information and ITK target dependency information. This will allow other projects to build against the C++ classes provided.

For more information on generation of the required files, see the [ITKModuleTemplate](https://github.com/InsightSoftwareConsortium/ITKModuleTemplate) and documentation on [How To Create A Module](https://itk.org/ITKSoftwareGuide/html/Book1/ITKSoftwareGuide-Book1ch9.html#x55-1490009) in the ITK Software Guide.

**Comment by plooney** [comment]
@thewtex If i try to build outside the ITK buildpath I get 

CMake Error at CMakeLists.txt:22 (include):
   include could not find load file:

     ITKModuleExternal

**Comment by thewtex** [comment]
@plooney with what version of ITK?

**Comment by plooney** [comment]
4.13.1

**Comment by thewtex** [comment]
Did you try these steps?

```
mkdir kretz-module-build
cd kretz-module-build
cmake -DITK_DIR=/path/to/ITK-build /path/to/kretz
make
cd ..

mkdir kretz-programs-build
cd kretz-programs-build
cmake -DITK_DIR=/path/to/ITK-build /path/to/kretz/examples
make
```

**Comment by plooney** [comment]
Working now.

**Comment by thewtex** [comment]
Great!
