### ISSUE TITLE
Enable automated CI testing

### ISSUE THREAD

**Issue by thewtex** [plooney/kretz#9]
Free GitHub services are available (Azure Pipelines, CircleCI, TravisCI, AppVeyor).

The ITKModuleTemplate can be used to generate some of these configurations -- Currently CircleCI provides module C++ tests, all three provide Python package generation tests, but these are only needed if [Python wrapping configuration](https://itk.org/ITKSoftwareGuide/html/Book1/ITKSoftwareGuide-Book1ch9.html#x55-1560009.5) is added.

**Comment by plooney** [comment]
Added travis CI file. Cannot build KRETZ with ITK 4.9 binaries available for most recent version 16.04 of Ubuntu. Tried building ITK from source but timing out after 50 minutes

**Comment by gordon-n-stevenson** [comment]
I'm really behind and getting up to speed with some of these tools but I think this sort of guide is the route forward (?) 

https://blog.kitware.com/automated-tests-on-github-for-your-itk-dependent-project-with-circleci-and-docker/

**Comment by plooney** [comment]
@gordon-n-stevenson That looks promising.  I've had a go at implementing that but docker hub isn't playing ball with github and I am getting all sorts of errors trying to link Dockler-hub with my github account

**Comment by plooney** [comment]
Having trouble installing libboost in the docker container. Related tests have been commented out.
